#!/bin/bash
baseMTime=0
while :; do
nowMTime=`stat -c %Y game.c`
if ((baseMTime != nowMTime)); then
baseMTime=$nowMTime
echo "----"
gcc -o game.so game.c -lX11 -lGL -lGLU -std=gnu99 -O3 -fomit-frame-pointer -ffast-math -mno-ieee-fp -D___BUILD_LINUX_GNU_X86_64___ -fno-exceptions -fno-asynchronous-unwind-tables -fno-zero-initialized-in-bss -fpic -shared
fi
sleep 0.1
done
